### ISSUE TITLE
有没有想法用typescript来开发？

### ISSUE THREAD

**Issue by yanche** [waditu/tushare.js#15]
主要是觉得js项目如果做大了 修改/debug 起来挺麻烦的
如果你们觉得可以/感兴趣 我来帮忙升级

**Comment by ruanyl** [comment]
我是持openmind的，但是我的感觉是tushare主要是帮忙做了一个`http request`，似乎并不能从`类型` beneficial 太多。可能我理解错了，回头再研究研究。

**Comment by strengthening** [comment]
其实没必要,都是封装的抓数据的接口,单元测试+console.log()足够了.没有很复杂的逻辑

**Comment by yanche** [comment]
这倒是
还有一个好处是类型相当于自说明文档
就不用对每个api在文档里列举字段以及类型了


strengthening <notifications@github.com>于2017年2月16日 周四上午5:49写道：

**Comment by yanche** [comment]
另外tushare是没有服务器的吗？历史后复权这样的数据也是一个实时api的agent？
我之前的理解是这个nodejs lib是call tushare某个服务器的client

**Comment by ruanyl** [comment]
没有，所有数据来自网上

**Comment by PhilTheAir** [comment]
不会typescript😊😉es6就行了
