### ISSUE TITLE
start 和 end 无效

### ISSUE THREAD

**Issue by callmewhy** [waditu/tushare.js#5]
`getHistory` 中的 start 和 end 参数并没有在 priceURL 中传入。。。导致无法设置起始时间和结束时间。

**Comment by callmewhy** [comment]
看了下 TuShare 源码，似乎是获取之后用 Pandas 做了过滤。。。看来 API 本身没有这个功能=。=

**Comment by ruanyl** [comment]
是的，start 和 end 并没有传入api url。我想应该有其它数据来源支持传入时间。其实tushare.js修改了一些数据的来源，像龙虎榜和大宗交易的数据是从网易财经获取的。如果你知道有其他更好的api，非常欢迎pull request :+1:

**Comment by callmewhy** [comment]
希望后面有机会可以参与进来：）最近有些忙。不过感觉没有 Numpy Pandas 这样的库 JS 处理数据略繁琐

**Comment by hustcer** [comment]
现在的接口是不是不能获取除权后的价格？

**Comment by ruanyl** [comment]
@hustcer 获取历史数据的接口好像没有除权的参数。除权数据应该在另一个接口，https://github.com/waditu/tushare/blob/7b39a4e1fe5fc70ea6d3c9058ebf30a6c959f4cf/tushare/stock/trading.py#L371

**Comment by hustcer** [comment]
嗯，要是能支持下就好了~ 😄
