### ISSUE TITLE
Upgrade superagent please

### ISSUE THREAD

**Issue by hustcer** [waditu/tushare.js#9]
Related issue: https://github.com/visionmedia/superagent/issues/313#issuecomment-250873791

> We know 1.8 is buggy — we've already fixed those bugs in later versions. Especially 2.2 and later removed many double callback problems. Please upgrade.

**Comment by ruanyl** [comment]
The latest version of `tushare.js` do not rely on `superagent` any more. I should do some cleanup at some point, thanks anyway :)
